source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3' 
gem 'roo'
gem 'roo-xls'
gem 'activerecord'
gem 'rake'
gem 'puma'
gem 'webrick'
gem 'rack'      
gem 'rackup'
gem 'caxlsx'  
gem 'tempfile'